name = "omb-v3-api"
main = "main.py"
compatibility_date = "2024-01-01"

[env.development]
name = "omb-v3-api-dev"

[env.production]
name = "omb-v3-api-prod"

# Environment variables (will be set via wrangler secret)
# JWT_SECRET_KEY
# STRIPE_SECRET_KEY 
# STRIPE_WEBHOOK_SECRET
# GEMINI_API_KEY
# ANTHROPIC_API_KEY

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "omb-v3-database"
database_id = "your-database-id-here"

# R2 Storage binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "omb-v3-modules"

# Python configuration
[python]
install_command = "pip install -r requirements.txt" 